---
kind: pipeline
type: docker
name: build docker image

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: pacbard/drone-ipfs-deploy
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

...
