#!/bin/bash
set -e

IPFS_DEPLOY_OPTIONS=""

if [ -n "$PLUGIN_SORUCE" ]
then
    IPFS_DEPLOY_OPTIONS="$PLUGIN_SOURCE"
fi

IPFS_DEPLOY_OPTIONS="$IPFS_DEPLOY_OPTIONS --no-clipboard"

if [ -n "$PLUGIN_PINNING_SERVICE" ]
then
    IPFS_DEPLOY_OPTIONS="$IPFS_DEPLOY_OPTIONS -p $PLUGIN_PINNING_SERVICE"
fi

if [ -n "$PLUGIN_DNS_SERVICE" ]
then
    IPFS_DEPLOY_OPTIONS="$IPFS_DEPLOY_OPTIONS -d $PLUGIN_DNS_SERVICE"
fi

hash=`npx ipfs-deploy $IPFS_DEPLOY_OPTIONS | tail -1`
echo $hash >> .hash

